env:
  browser: true
  es2021: true
extends:
  - plugin:vue/essential
  - standard
  - "@nuxtjs/eslint-config-typescript"
  - prettier
parserOptions:
  ecmaVersion: latest
  parser: "@typescript-eslint/parser"
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules: {}
